# Generated by Django 3.0rc1 on 2019-12-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('idname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
